<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <IsAotCompatible>true</IsAotCompatible>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="System.Data.SQLite"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\VRCX.Core.Shared\VRCX.Core.Shared.csproj"/>
    </ItemGroup>

</Project>
