<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <DefineConstants>VRCX_CORE</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NLog"/>
        <PackageReference Include="Newtonsoft.Json"/>
        <PackageReference Include="DiscordRichPresence"/>
        <PackageReference Include="System.Data.SQLite"/> <!--DO NOT UPGRADE-->
        <PackageReference Include="System.Management"/>
        <PackageReference Include="SixLabors.ImageSharp"/>
        <PackageReference Include="SixLabors.ImageSharp.Drawing"/>
        <PackageReference Include="Websocket.Client"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection"/>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="librsync.net">
            <HintPath>..\..\..\Dotnet\libs\librsync.net.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\..\Version">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
